initial_paths:
  path_progresESM: 'train_LAMLP_ESM2.txt'
  checkpoint_pathESM: '../checkpoints/ESM2_only/Global/AllMeltome_composed_loss_globalAvgtm/'
  path_progresPiFold: 'train_LAMLP_PiFold.txt'
  checkpoint_pathPiFold: '../checkpoints/PiFold_only/Global/AllMeltome_composed_loss_globalAvgtm/'
  path_progresMix: 'train_LAMLP_Mix.txt'
  checkpoint_pathMix: '../checkpoints/Mix/Global/AllMeltome_composed_loss_globalAvgtm/'
  ESM_source: 'ESM2_single_embeddings_nobatches'
  PiFold_source: 'PiFold_if1_embeddings'
  prepro_train_emb_ESM: 'train_set_embeddings_ESM2_Ecoli3.pth'
  prepro_test_emb_ESM: 'test_set_embeddings_ESM2_Ecoli3.pth'
  prepro_val_emb_ESM: 'val_set_embeddings_ESM2_Ecoli3.pth'
  prepro_train_emb_PiFold: 'train_set_IFPiFoldembeddings_Ecoli3.pth'
  prepro_test_emb_PiFold: 'test_set_IFPiFoldembeddings_Ecoli3.pth'
  prepro_val_emb_PiFold: 'val_set_IFPiFoldembeddings_Ecoli3.pth'
  output_metrics_ESM_only: './metrics_global_vs_species_loss_composed/ESM_only/HAOEC.txt'
  output_metrics_PiFold_only: './metrics_global_vs_species_loss_composed/PiFold_only/HAOEC.txt'
  output_metrics_Both: './metrics_global_vs_species_loss_composed/Both/HAOEC.txt'
organism:
  Global: False
  organism: 'HAOEC'
  keyword: ''
meltome:
  path_meltome: '../datasets/FLIP/splits/meltome/splits/mixed_split.csv'
  complete_meltome_db: '../datasets/FLIP/splits/meltome/full_dataset_sequences.fasta'
Pifold_pretrain:
  svpath: '../ref_models/PiFold/results/'
structures_path:
  structuredir: '../datasets/Structures/'
  meltome_struct_dir_labels: '../datasets/'
ESM2embeddings:
  dir_pre_generated_embeddings: '../prepro_embeddings/'
